### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by kjac3585** [luluhoc/home-cinema-toolkit#7]
Windows 10, Docker v19.03.13, Radarr v3.0.0.4065

Just installed via docker, the gui loads in my browser but can't get it to talk to radar. I tried using localhost:port and IP:port but it just gives me an error "server error - getting movies from radar"

```
(node:41) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 46628)
(node:41) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 46630)
(node:41) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 46638)
(node:41) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 46634)
(node:41) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 46636)
(node:41) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /usr/src/app/server/routes/api/v1/rating.js:141:36
(node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 46639)
{
  radarrUrl: 'localhost:38083',
  radarrApi: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  keyOmdb: 'http://www.omdbapi.com/?apikey=XXXXXXXX',
  v3: true,
  addExclusion: true,
  deleteFiles: true
}
Error: connect ECONNREFUSED 127.0.0.1:38083
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 38083,
  config: {
    url: 'http://localhost:38083/api/v3/movie',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'request',
      'X-Api-Key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v3/movie',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '38083',
      nativeProtocols: [Object],
      pathname: '/api/v3/movie'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /api/v3/movie HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: request\r\n' +
        'X-Api-Key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n' +
        'Host: localhost:38083\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v3/movie',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://localhost:38083/api/v3/movie',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
{
  radarrUrl: 'localhost:38083',
  radarrApi: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  keyOmdb: 'http://www.omdbapi.com/?apikey=XXXXXXXX',
  v3: true,
  addExclusion: true,
  deleteFiles: true
}
Error: connect ECONNREFUSED 127.0.0.1:38083
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 38083,
  config: {
    url: 'http://localhost:38083/api/v3/movie',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'request',
      'X-Api-Key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v3/movie',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '38083',
      nativeProtocols: [Object],
      pathname: '/api/v3/movie'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /api/v3/movie HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: request\r\n' +
        'X-Api-Key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n' +
        'Host: localhost:38083\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v3/movie',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://localhost:38083/api/v3/movie',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
{
  radarrUrl: 'localhost:38083',
  radarrApi: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  keyOmdb: 'http://www.omdbapi.com/?apikey=XXXXXXXX',
  v3: true,
  addExclusion: true,
  deleteFiles: true
}
Error: connect ECONNREFUSED 127.0.0.1:38083
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 38083,
  config: {
    url: 'http://localhost:38083/api/v3/movie',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'request',
      'X-Api-Key': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v3/movie',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '38083',
      nativeProtocols: [Object],
      pathname: '/api/v3/movie'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /api/v3/movie HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: request\r\n' +
        'X-Api-Key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n' +
        'Host: localhost:38083\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v3/movie',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://localhost:38083/api/v3/movie',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by kjac3585** [comment]
I think i've made some progress, but still running into some errors. I changed the IP from localhost to my win10 pc's local IP address, which is the host of my radar installation. A similar error and new error popped up even though it appears to have been able to talk with radar this time.

```
$ nodemon start.js --prefix server --ignore db/

[nodemon] 2.0.5

[nodemon] to restart at any time, enter `rs`

[nodemon] watching path(s): *.*

[nodemon] watching extensions: js,mjs,json

[nodemon] starting `node start.js --prefix server`

Home Cinema Toolkit has started on 12400!

{

radarrUrl: '192.168.2.7:38083',

radarrApi: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',

keyOmdb: 'XXXXXXXX',

v3: true,

addExclusion: true,

deleteFiles: true

}

Got movies from radarr...

Searching movies in OMDB...

Waiting for OMDB

Error: connect ECONNREFUSED 104.20.135.15:80

at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {

errno: -111,

code: 'ECONNREFUSED',

syscall: 'connect',

address: '104.20.135.15',

port: 80,

config: {

url: 'http://www.omdbapi.com/?apikey=XXXXXXXX&i=tt5688932',

headers: {

Accept: 'application/json, text/plain, */*',

'User-Agent': 'axios/0.20.0'

},

transformRequest: [ [Function: transformRequest] ],

transformResponse: [ [Function: transformResponse] ],

timeout: 0,

adapter: [Function: httpAdapter],

xsrfCookieName: 'XSRF-TOKEN',

xsrfHeaderName: 'X-XSRF-TOKEN',

maxContentLength: -1,

maxBodyLength: -1,

validateStatus: [Function: validateStatus],

method: 'get',

data: undefined

},

request: <ref *1> Writable {

_writableState: WritableState {

objectMode: false,

highWaterMark: 16384,

finalCalled: false,

needDrain: false,

ending: false,

ended: false,

finished: false,

destroyed: false,

decodeStrings: true,

defaultEncoding: 'utf8',

length: 0,

writing: false,

corked: 0,

sync: true,

bufferProcessing: false,

onwrite: [Function: bound onwrite],

writecb: null,

writelen: 0,

afterWriteTickInfo: null,

buffered: [],

bufferedIndex: 0,

allBuffers: true,

allNoop: true,

pendingcb: 0,

prefinished: false,

errorEmitted: false,

emitClose: true,

autoDestroy: true,

errored: null,

closed: false

},

_events: [Object: null prototype] {

response: [Function: handleResponse],

error: [Function: handleRequestError]

},

_eventsCount: 2,

_maxListeners: undefined,

_options: {

maxRedirects: 21,

maxBodyLength: 10485760,

protocol: 'http:',

path: '/?apikey=XXXXXXXX&i=tt5688932',

method: 'GET',

headers: [Object],

agent: undefined,

agents: [Object],

auth: undefined,

hostname: 'www.omdbapi.com',

port: null,

nativeProtocols: [Object],

pathname: '/',

search: '?apikey=XXXXXXXX&i=tt5688932'

},

_ended: true,

_ending: true,

_redirectCount: 0,

_redirects: [],

_requestBodyLength: 0,

_requestBodyBuffers: [],

_onNativeResponse: [Function (anonymous)],

_currentRequest: ClientRequest {

_events: [Object: null prototype],

_eventsCount: 7,

_maxListeners: undefined,

outputData: [],

outputSize: 0,

writable: true,

destroyed: false,

_last: true,

chunkedEncoding: false,

shouldKeepAlive: false,

useChunkedEncodingByDefault: false,

sendDate: false,

_removedConnection: false,

_removedContLen: false,

_removedTE: false,

_contentLength: 0,

_hasBody: true,

_trailer: '',

finished: true,

_headerSent: true,

socket: [Socket],

_header: 'GET /?apikey=XXXXXXXX&i=tt5688932 HTTP/1.1\r\n' +

'Accept: application/json, text/plain, */*\r\n' +

'User-Agent: axios/0.20.0\r\n' +

'Host: www.omdbapi.com\r\n' +

'Connection: close\r\n' +

'\r\n',

_keepAliveTimeout: 0,

_onPendingData: [Function: noopPendingOutput],

agent: [Agent],

socketPath: undefined,

method: 'GET',

maxHeaderSize: undefined,

insecureHTTPParser: undefined,

path: '/?apikey=XXXXXXXX&i=tt5688932',

_ended: false,

res: null,

aborted: false,

timeoutCb: null,

upgradeOrConnect: false,

parser: null,

maxHeadersCount: null,

reusedSocket: false,

host: 'www.omdbapi.com',

protocol: 'http:',

_redirectable: [Circular *1],

[Symbol(kCapture)]: false,

[Symbol(kNeedDrain)]: false,

[Symbol(corked)]: 0,

[Symbol(kOutHeaders)]: [Object: null prototype]

},

_currentUrl: 'http://www.omdbapi.com/?apikey=XXXXXXXX&i=tt5688932',

[Symbol(kCapture)]: false

},

response: undefined,

isAxiosError: true,

toJSON: [Function: toJSON]

}

(node:41) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined

at /usr/src/app/server/routes/api/v1/rating.js:141:36

at runMicrotasks (<anonymous>)

at processTicksAndRejections (internal/process/task_queues.js:93:5)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

(node:41) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by luluhoc** [comment]
It seems that radarr isn't published on network, can you connect to radarr from your phone? Please check if radarr port is allowed in your firewall in windows.

**Comment by luluhoc** [comment]
It seems that there is some problem with your api key, can you try manually if your key works?

**Comment by kjac3585** [comment]
I redacted the api keys with X's, not sure if that was obvious or not. I don't have any issues accessing radarr from my phone using nzb360, inside or outside my network. So I don't think there's any port forwarding issues. The imdb API link seems to work fine, brought up the name ratings etc... for that specific movie. 

I am brand new to Docker, however... so I'm a little worried that I could be missing something important on that front since it's all so new. It seems like I've got it up and running correctly but...

**Comment by luluhoc** [comment]
Yes it's obvious, is it the free api key?

Please try this api key and let me know if it works 
`thewdb`

**Comment by kjac3585** [comment]
I tried that key and get the same errors "error fetching omdb"

**Comment by luluhoc** [comment]
Can You give me logs?

**Comment by kjac3585** [comment]
https://pastebin.com/Atwpd4Zj

That's the beginning of the log and as much as I could capture before it starts truncating, but it's just more of the same. The very end of the log is:

```
(node:48) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined

at /usr/src/app/server/routes/api/v1/rating.js:141:36

(node:48) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12896)
```

**Comment by luluhoc** [comment]
It looks like container can't connect to Omdb api, does your container have access to the internet? Every request to omdb is timed out.

**Comment by kjac3585** [comment]
I think it does? I opened the CLI on the HCT container and pinged the same OMDB IP:

```
# ping 104.20.135.15
PING 104.20.135.15 (104.20.135.15) 56(84) bytes of data.
64 bytes from 104.20.135.15: icmp_seq=1 ttl=37 time=35.9 ms
64 bytes from 104.20.135.15: icmp_seq=2 ttl=37 time=29.0 ms
64 bytes from 104.20.135.15: icmp_seq=3 ttl=37 time=29.0 ms
64 bytes from 104.20.135.15: icmp_seq=4 ttl=37 time=28.6 ms
64 bytes from 104.20.135.15: icmp_seq=5 ttl=37 time=28.0 ms
64 bytes from 104.20.135.15: icmp_seq=6 ttl=37 time=29.0 ms
64 bytes from 104.20.135.15: icmp_seq=7 ttl=37 time=30.4 ms
^C
--- 104.20.135.15 ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6007ms
rtt min/avg/max/mdev = 28.043/30.028/35.978/2.516 ms
```

**Comment by luluhoc** [comment]
I’m gonna make some changes to repo and I’ll add some console logs to see what is the problem.

**Comment by kjac3585** [comment]
https://pastebin.com/ji06f4N3

New logs running the latest update, still no bueno, but there's some more information in the logs at least.

**Comment by luluhoc** [comment]
How many movies do you have?

**Comment by kjac3585** [comment]
about 6,000 movies. That's why I purchased an API key from OMDB so it wouldn't be limited, but it made no difference.

**Comment by luluhoc** [comment]
Can you send me your DB? I will try it myself.

**Comment by kjac3585** [comment]
sure, i'll PM you a link on your reddit account. password will be HCT-2020

**Comment by luluhoc** [comment]
I'm waiting on your message

**Comment by kjac3585** [comment]
hmm it shows as being sent 22hrs ago to lulu455, maybe it was flagged as spam since it has a mega.nz link. Is there an email address I can send it to?

**Comment by luluhoc** [comment]
send it to luludisposable@gmail.com

**Comment by kjac3585** [comment]
sent

**Comment by luluhoc** [comment]
Thanks,

I'm trying to replicate the error for now without success...
![image](https://user-images.githubusercontent.com/22813220/99744447-062f5580-2ad8-11eb-854d-dd0cb69f2b2a.png)
![image](https://user-images.githubusercontent.com/22813220/99744458-0a5b7300-2ad8-11eb-9114-09f70f2d1e5a.png)

I will try it in docker because for now I'm running it in dev env.

**Comment by luluhoc** [comment]
I think the problem lays with optimization, when I run it in docker it crashes, I will try to optimize it and I'll let you know. I never tried it with DB with over 6k movies.

**Comment by kjac3585** [comment]
awesome thanks for looking into it. I feel like I have a pretty large collection, but then I've seen some massive collections of nearly 50,000 movies...crazy stuff. thank again.

**Comment by luluhoc** [comment]
Just a quick update :) I did not forget about you ;) I think I found the problem and I should be able to optimize it ;) I'm gonna find time soon. Btw thanks for coffee.

**Comment by luluhoc** [comment]
I pushed a commit it is building on docker, It will be a little bit slower but it should be more stable and it should work with big radarr DB. Please let me know if it works for you.

**Comment by kjac3585** [comment]
I installed the new update and so far there's no errors, but it's been "Getting IMDB RATING" for about 30 minutes now with no results so far. About how long should I expect a 6,000 movie db to take? thanks

```
yarn run v1.22.5

$ nodemon start.js --prefix server --ignore db/

[nodemon] 2.0.6

[nodemon] to restart at any time, enter `rs`

[nodemon] watching path(s): *.*

[nodemon] watching extensions: js,mjs,json

[nodemon] starting `node start.js --prefix server`

Home Cinema Toolkit has started on 12400!

{

radarrUrl: '192.168.2.7:38083',

radarrApi: 'XXXXXXXXXXXXXXXXXXXX',

keyOmdb: 'XXXXXXXX',

v3: true,

addExclusion: true,

deleteFiles: true

}

Got movies from radarr...

{

radarrUrl: '192.168.2.7:38083',

radarrApi: 'XXXXXXXXXXXXXXXXXXXXXXX',

keyOmdb: 'XXXXXXXXXX',

v3: true,

addExclusion: true,

deleteFiles: true

}

Searching movies in OMDB...

DB LENGTH 6042
```

**Comment by kjac3585** [comment]
after about an hour some errors are popping up on the logs

[https://pastebin.com/ray4zTXm](https://pastebin.com/ray4zTXm)

**Comment by luluhoc** [comment]
please try it now

**Comment by kjac3585** [comment]
another error

[https://pastebin.com/ry8UvR8M](https://pastebin.com/ry8UvR8M)

**Comment by luluhoc** [comment]
oh sorry, i forgot one variable, it should be good now :)

**Comment by kjac3585** [comment]
awesome, it works now. I did get some server errors when trying to delete some movies, not sure what caused it as the movies aren't downloaded yet so shouldn't be a permissions issue. 

[https://pastebin.com/tqG8niSq](https://pastebin.com/tqG8niSq)

I noticed that when I search for something it has to pull the data from imdb again for each query, takes about 15 mins for my collection...not a huge deal, but have you considered storing the imdb ratings in a local database so that it only pulls the data once for each movie? I know imdb ratings aren't exactly static, but they don't seem to change too much after a movie has been out for a year maybe?

Also, I've noticed a couple little things, possibly bugs or just suggestions, should I make a new thread for each one or keep it in this thread?

Thanks!

**Comment by luluhoc** [comment]
> awesome, it works now. I did get some server errors when trying to delete some movies, not sure what caused it as the movies aren't downloaded yet so shouldn't be a permissions issue.
> 
> https://pastebin.com/tqG8niSq
> 
> I noticed that when I search for something it has to pull the data from imdb again for each query, takes about 15 mins for my collection...not a huge deal, but have you considered storing the imdb ratings in a local database so that it only pulls the data once for each movie? I know imdb ratings aren't exactly static, but they don't seem to change too much after a movie has been out for a year maybe?
> 
> Also, I've noticed a couple little things, possibly bugs or just suggestions, should I make a new thread for each one or keep it in this thread?
> 
> Thanks!

I will investigate these deleting errors, as I didn't do it after the major changes to the code. I will let you know.

Yes for sure I'm considering it, I think I will store the IMDB data with an expiration date. For example, the program will store IMDB data for one month and after one month it will pull new data. I think for older movies the program will pull data after 6 months, cause as you have said there is no too much change for the movies that have been out for a year.

Yes please open new issues. I will close this issue as the problem with it is resolved. We will follow the new issues in the new that you opened.

Thank you also!
