### ISSUE TITLE
404 NOT FOUND - Probably bad Radarr link

### ISSUE THREAD

**Issue by jkempson** [luluhoc/home-cinema-toolkit#8]
I'm running radarr in a docker container on the same machine as HCT, also running in a continer.

Radarr runs on http://nas.lan:7878
HCT runs on http://nas.lan:12400

I've tried running HCT on bridge & host network but can't get it to see Radarr

Possibly unrelated but what should I be doing with this part of the docker settings? 
`-v /path/to/db:/usr/src/app/db \`

If I pull up a console in the container I can ping nas.lan and also I'm able to successfully run
`wget nas.lan:7878`

Pastebin of log (APIs redacted)
https://pastebin.com/xB0KMeyT

It looks like Radarr is seeing requests from HCT. I'm seeing this in the Radarr logs when I click "search" in HCT.
`[Debug] Api: [GET] /api/v3/movie: 404.NotFound (1 ms) `

**Comment by luluhoc** [comment]
You need to provide IP address instead of a domain nas.lan, cause docker can't see it.

**Comment by jkempson** [comment]
Thanks for the support!
Yeah, I should have mentioned I'd tried IP address too but it still didn't work. I unchecked api V3 in the settings and I've got a bit further now!

2020-12-04T14:26:56.898806314Z Got movies from radarr...

2020-12-04T14:27:00.332245496Z {

2020-12-04T14:27:00.332392205Z   radarrUrl: '192.168.0.3:7878',

2020-12-04T14:27:00.332415547Z   radarrApi: '***',

2020-12-04T14:27:00.332458113Z   keyOmdb: '***',

2020-12-04T14:27:00.332478614Z   v3: false,

2020-12-04T14:27:00.332496927Z   addExclusion: true,

2020-12-04T14:27:00.332535306Z   deleteFiles: true

2020-12-04T14:27:00.332556235Z }

2020-12-04T14:27:00.332767534Z Searching movies in OMDB...

2020-12-04T14:27:00.339717202Z (node:41) UnhandledPromiseRejectionWarning: ReferenceError: moviesFromDb is not defined

2020-12-04T14:27:00.339816284Z     at /usr/src/app/server/routes/api/v1/rating.js:144:31

2020-12-04T14:27:00.339861402Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)

2020-12-04T14:27:00.339881554Z (Use `node --trace-warnings ...` to show where the warning was created)

2020-12-04T14:27:00.340184787Z (node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

2020-12-04T14:27:00.340234481Z (node:41) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by luluhoc** [comment]
Please update the docker container cause there was a bug in my code from earlier it is now handled.

**Comment by luluhoc** [comment]
The docker container is building right now it should be ready in 5 min.

**Comment by luluhoc** [comment]
Please try it now

**Comment by jkempson** [comment]
Oh my it's working! Thank you!

**Comment by luluhoc** [comment]
please start the repo if you like it :)

**Comment by jkempson** [comment]
Will do :)
